 .-----------------------------------------------------------.
| Send and receive messages.  USAGE:                         |
| SITE MSG READ                          - read your msgs    |
| SITE MSG SAVE                          - move msgs to inbox|
| SITE MSG PURGE                         - dele msgs in trash|
| SITE MSG TREAD                         - read msgs in trash|
| SITE MSG <username> <message>          - send a message    |
| SITE MSG { <user1> <user2> } <message> - send to mult users|
| SITE MSG =<group> <message>            - send msg to group |
| SITE MSG * <message>                   - send msg to every1|  
 `-----------------------------------------------------------'
